name: Deploy

on:
  push:

env:
  VERSION: '3.24.5'
  BASE_DIR: '/dart_ast_viewer/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: pubspec-${{ hashFiles('./pubspec.lock') }}
          restore-keys: pubspec-

      - uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{ env.VERSION }}
          cache: true

      - name: Setup & Build
        run: |
          flutter pub get
          flutter build web --base-href="${{ env.BASE_DIR }}" --profile

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
